CREATE TABLE TH2018.HTX_GIRO
 (NO_REK        VARCHAR(12)     NOT NULL,
  KD_CAB        CHARACTER(3)    NOT NULL,
  TGL_TX        DATE            NOT NULL,
  TIME_STAMP    TIMESTAMP       NOT NULL,
  KD_USER       CHARACTER(5)    NOT NULL,
  KD_TX         CHARACTER(3)    NOT NULL,
  KET_TX        VARCHAR(30)     NOT NULL,
  NO_ARSIP      VARCHAR(10)     NOT NULL,
  SALDO_AKHIR   DECIMAL(15, 2)  NOT NULL,
  DB_KR         CHARACTER(1)    NOT NULL,
  JUMLAH_TX     DECIMAL(15, 2)  NOT NULL,
  KD_SPV        CHARACTER(5)    NOT NULL,
  KD_CAB_LOKTX  CHARACTER(3)    NOT NULL
 )
  DATA CAPTURE NONE
  IN USERSPACE2;

ALTER TABLE TH2018.HTX_GIRO
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

ALTER TABLE TH2018.HTX_GIRO
  ADD CONSTRAINT SQL141231032120540 PRIMARY KEY
   (NO_REK,
    KD_CAB,
    TGL_TX,
    TIME_STAMP
   );

   --

   CREATE TABLE TH2018.HTX_SAVE
 (NO_REK        VARCHAR(12)     NOT NULL,
  KD_CAB        CHARACTER(3)    NOT NULL,
  TGL_TX        DATE            NOT NULL,
  TIME_STAMP    TIMESTAMP       NOT NULL,
  KD_USER       CHARACTER(5)    NOT NULL,
  KD_TX         CHARACTER(3)    NOT NULL,
  KET_TX        VARCHAR(30)     NOT NULL,
  NO_ARSIP      VARCHAR(10)     NOT NULL,
  SALDO_AKHIR   DECIMAL(15, 2)  NOT NULL,
  DB_KR         CHARACTER(1)    NOT NULL,
  JUMLAH_TX     DECIMAL(15, 2)  NOT NULL,
  KD_SPV        CHARACTER(5)    NOT NULL,
  KD_CAB_LOKTX  CHARACTER(3)    NOT NULL
 )
  DATA CAPTURE NONE
  IN USERSPACE2;

ALTER TABLE TH2018.HTX_SAVE
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

ALTER TABLE TH2018.HTX_SAVE
  ADD CONSTRAINT SQL141231032120540 PRIMARY KEY
   (NO_REK,
    KD_CAB,
    TGL_TX,
    TIME_STAMP
   );

   --

   CREATE TABLE TH2018.HTX_DEPO
 (NO_REK        VARCHAR(12)     NOT NULL,
  KD_CAB        CHARACTER(3)    NOT NULL,
  TGL_TX        DATE            NOT NULL,
  TIME_STAMP    TIMESTAMP       NOT NULL,
  KD_USER       CHARACTER(5)    NOT NULL,
  KD_TX         CHARACTER(3)    NOT NULL,
  KET_TX        VARCHAR(30)     NOT NULL,
  NO_ARSIP      VARCHAR(10)     NOT NULL,
  SALDO_AKHIR   DECIMAL(15, 2)  NOT NULL,
  DB_KR         CHARACTER(1)    NOT NULL,
  JUMLAH_TX     DECIMAL(15, 2)  NOT NULL,
  KD_SPV        CHARACTER(5)    NOT NULL,
  KD_CAB_LOKTX  CHARACTER(3)    NOT NULL
 )
  DATA CAPTURE NONE
  IN USERSPACE2;

ALTER TABLE TH2018.HTX_DEPO
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

ALTER TABLE TH2018.HTX_DEPO
  ADD CONSTRAINT SQL141231032120540 PRIMARY KEY
   (NO_REK,
    KD_CAB,
    TGL_TX,
    TIME_STAMP
   );

   --

   CREATE TABLE TH2018.HTX_MURABAHAH
 (NO_REK        VARCHAR(12)     NOT NULL,
  KD_CAB        CHARACTER(3)    NOT NULL,
  TGL_TX        DATE            NOT NULL,
  TIME_STAMP    TIMESTAMP       NOT NULL,
  KD_USER       CHARACTER(5)    NOT NULL,
  KD_TX         CHARACTER(3)    NOT NULL,
  KET_TX        VARCHAR(30)     NOT NULL,
  NO_ARSIP      VARCHAR(10)     NOT NULL,
  SALDO_AKHIR   DECIMAL(15, 2)  NOT NULL,
  DB_KR         CHARACTER(1)    NOT NULL,
  JUMLAH_TX     DECIMAL(15, 2)  NOT NULL,
  KD_SPV        CHARACTER(5)    NOT NULL,
  KD_CAB_LOKTX  CHARACTER(3)    NOT NULL
 )
  DATA CAPTURE NONE
  IN USERSPACE2;

ALTER TABLE TH2018.HTX_MURABAHAH
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

ALTER TABLE TH2018.HTX_MURABAHAH
  ADD CONSTRAINT SQL141231032120540 PRIMARY KEY
   (NO_REK,
    KD_CAB,
    TGL_TX,
    TIME_STAMP
   );

   --

   CREATE TABLE TH2018.HTX_ISTISHNA
 (NO_REK        VARCHAR(12)     NOT NULL,
  KD_CAB        CHARACTER(3)    NOT NULL,
  TGL_TX        DATE            NOT NULL,
  TIME_STAMP    TIMESTAMP       NOT NULL,
  KD_USER       CHARACTER(5)    NOT NULL,
  KD_TX         CHARACTER(3)    NOT NULL,
  KET_TX        VARCHAR(30)     NOT NULL,
  NO_ARSIP      VARCHAR(10)     NOT NULL,
  SALDO_AKHIR   DECIMAL(15, 2)  NOT NULL,
  DB_KR         CHARACTER(1)    NOT NULL,
  JUMLAH_TX     DECIMAL(15, 2)  NOT NULL,
  KD_SPV        CHARACTER(5)    NOT NULL,
  KD_CAB_LOKTX  CHARACTER(3)    NOT NULL
 )
  DATA CAPTURE NONE
  IN USERSPACE2;

ALTER TABLE TH2018.HTX_ISTISHNA
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

ALTER TABLE TH2018.HTX_ISTISHNA
  ADD CONSTRAINT SQL141231032120540 PRIMARY KEY
   (NO_REK,
    KD_CAB,
    TGL_TX,
    TIME_STAMP
   );

   --

   CREATE TABLE TH2018.HTX_SALAM
 (NO_REK        VARCHAR(12)     NOT NULL,
  KD_CAB        CHARACTER(3)    NOT NULL,
  TGL_TX        DATE            NOT NULL,
  TIME_STAMP    TIMESTAMP       NOT NULL,
  KD_USER       CHARACTER(5)    NOT NULL,
  KD_TX         CHARACTER(3)    NOT NULL,
  KET_TX        VARCHAR(30)     NOT NULL,
  NO_ARSIP      VARCHAR(10)     NOT NULL,
  SALDO_AKHIR   DECIMAL(15, 2)  NOT NULL,
  DB_KR         CHARACTER(1)    NOT NULL,
  JUMLAH_TX     DECIMAL(15, 2)  NOT NULL,
  KD_SPV        CHARACTER(5)    NOT NULL,
  KD_CAB_LOKTX  CHARACTER(3)    NOT NULL
 )
  DATA CAPTURE NONE
  IN USERSPACE2;

ALTER TABLE TH2018.HTX_SALAM
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

ALTER TABLE TH2018.HTX_SALAM
  ADD CONSTRAINT SQL141231032120540 PRIMARY KEY
   (NO_REK,
    KD_CAB,
    TGL_TX,
    TIME_STAMP
   );

   --

   CREATE TABLE TH2018.HTX_IJARAH
 (NO_REK        VARCHAR(12)     NOT NULL,
  KD_CAB        CHARACTER(3)    NOT NULL,
  TGL_TX        DATE            NOT NULL,
  TIME_STAMP    TIMESTAMP       NOT NULL,
  KD_USER       CHARACTER(5)    NOT NULL,
  KD_TX         CHARACTER(3)    NOT NULL,
  KET_TX        VARCHAR(30)     NOT NULL,
  NO_ARSIP      VARCHAR(10)     NOT NULL,
  SALDO_AKHIR   DECIMAL(15, 2)  NOT NULL,
  DB_KR         CHARACTER(1)    NOT NULL,
  JUMLAH_TX     DECIMAL(15, 2)  NOT NULL,
  KD_SPV        CHARACTER(5)    NOT NULL,
  KD_CAB_LOKTX  CHARACTER(3)    NOT NULL
 )
  DATA CAPTURE NONE
  IN USERSPACE2;

ALTER TABLE TH2018.HTX_IJARAH
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

ALTER TABLE TH2018.HTX_IJARAH
  ADD CONSTRAINT SQL141231032120540 PRIMARY KEY
   (NO_REK,
    KD_CAB,
    TGL_TX,
    TIME_STAMP
   );

   --

   CREATE TABLE TH2018.HTX_MUDHARABAH
 (NO_REK        VARCHAR(12)     NOT NULL,
  KD_CAB        CHARACTER(3)    NOT NULL,
  TGL_TX        DATE            NOT NULL,
  TIME_STAMP    TIMESTAMP       NOT NULL,
  KD_USER       CHARACTER(5)    NOT NULL,
  KD_TX         CHARACTER(3)    NOT NULL,
  KET_TX        VARCHAR(30)     NOT NULL,
  NO_ARSIP      VARCHAR(10)     NOT NULL,
  SALDO_AKHIR   DECIMAL(15, 2)  NOT NULL,
  DB_KR         CHARACTER(1)    NOT NULL,
  JUMLAH_TX     DECIMAL(15, 2)  NOT NULL,
  KD_SPV        CHARACTER(5)    NOT NULL,
  KD_CAB_LOKTX  CHARACTER(3)    NOT NULL
 )
  DATA CAPTURE NONE
  IN USERSPACE2;

ALTER TABLE TH2018.HTX_MUDHARABAH
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

ALTER TABLE TH2018.HTX_MUDHARABAH
  ADD CONSTRAINT SQL141231032120540 PRIMARY KEY
   (NO_REK,
    KD_CAB,
    TGL_TX,
    TIME_STAMP
   );

   --

   CREATE TABLE TH2018.HTX_QARD
 (NO_REK        VARCHAR(12)     NOT NULL,
  KD_CAB        CHARACTER(3)    NOT NULL,
  TGL_TX        DATE            NOT NULL,
  TIME_STAMP    TIMESTAMP       NOT NULL,
  KD_USER       CHARACTER(5)    NOT NULL,
  KD_TX         CHARACTER(3)    NOT NULL,
  KET_TX        VARCHAR(30)     NOT NULL,
  NO_ARSIP      VARCHAR(10)     NOT NULL,
  SALDO_AKHIR   DECIMAL(15, 2)  NOT NULL,
  DB_KR         CHARACTER(1)    NOT NULL,
  JUMLAH_TX     DECIMAL(15, 2)  NOT NULL,
  KD_SPV        CHARACTER(5)    NOT NULL,
  KD_CAB_LOKTX  CHARACTER(3)    NOT NULL
 )
  DATA CAPTURE NONE
  IN USERSPACE2;

ALTER TABLE TH2018.HTX_QARD
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

ALTER TABLE TH2018.HTX_QARD
  ADD CONSTRAINT SQL141231032120540 PRIMARY KEY
   (NO_REK,
    KD_CAB,
    TGL_TX,
    TIME_STAMP
   );

   --

   CREATE TABLE TH2018.HTX_INV
 (NO_REK        VARCHAR(12)     NOT NULL,
  KD_CAB        CHARACTER(3)    NOT NULL,
  TGL_TX        DATE            NOT NULL,
  TIME_STAMP    TIMESTAMP       NOT NULL,
  KD_USER       CHARACTER(5)    NOT NULL,
  KD_TX         CHARACTER(3)    NOT NULL,
  KET_TX        VARCHAR(30)     NOT NULL,
  NO_ARSIP      VARCHAR(10)     NOT NULL,
  SALDO_AKHIR   DECIMAL(15, 2)  NOT NULL,
  DB_KR         CHARACTER(1)    NOT NULL,
  JUMLAH_TX     DECIMAL(15, 2)  NOT NULL,
  KD_SPV        CHARACTER(5)    NOT NULL,
  KD_CAB_LOKTX  CHARACTER(3)    NOT NULL
 )
  DATA CAPTURE NONE
  IN USERSPACE2;

ALTER TABLE TH2018.HTX_INV
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

ALTER TABLE TH2018.HTX_INV
  ADD CONSTRAINT SQL141231032120540 PRIMARY KEY
   (NO_REK,
    KD_CAB,
    TGL_TX,
    TIME_STAMP
   );

   --

   CREATE TABLE TH2018.HTX_BGARANSI
 (NO_REK        VARCHAR(12)     NOT NULL,
  KD_CAB        CHARACTER(3)    NOT NULL,
  TGL_TX        DATE            NOT NULL,
  TIME_STAMP    TIMESTAMP       NOT NULL,
  KD_USER       CHARACTER(5)    NOT NULL,
  KD_TX         CHARACTER(3)    NOT NULL,
  KET_TX        VARCHAR(30)     NOT NULL,
  NO_ARSIP      VARCHAR(10)     NOT NULL,
  SALDO_AKHIR   DECIMAL(15, 2)  NOT NULL,
  DB_KR         CHARACTER(1)    NOT NULL,
  JUMLAH_TX     DECIMAL(15, 2)  NOT NULL,
  KD_SPV        CHARACTER(5)    NOT NULL,
  KD_CAB_LOKTX  CHARACTER(3)    NOT NULL
 )
  DATA CAPTURE NONE
  IN USERSPACE2;

ALTER TABLE TH2018.HTX_BGARANSI
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

ALTER TABLE TH2018.HTX_BGARANSI
  ADD CONSTRAINT SQL141231032120540 PRIMARY KEY
   (NO_REK,
    KD_CAB,
    TGL_TX,
    TIME_STAMP
   );

   --

   CREATE TABLE TH2018.HTX_LEDGER
 (NO_REK        VARCHAR(12)     NOT NULL,
  KD_CAB        CHARACTER(3)    NOT NULL,
  TGL_TX        DATE            NOT NULL,
  TIME_STAMP    TIMESTAMP       NOT NULL,
  KD_USER       CHARACTER(5)    NOT NULL,
  KD_TX         CHARACTER(3)    NOT NULL,
  KET_TX        VARCHAR(30)     NOT NULL,
  NO_ARSIP      VARCHAR(10)     NOT NULL,
  SALDO_AKHIR   DECIMAL(15, 2)  NOT NULL,
  DB_KR         CHARACTER(1)    NOT NULL,
  JUMLAH_TX     DECIMAL(15, 2)  NOT NULL,
  KD_SPV        CHARACTER(5)    NOT NULL,
  KD_CAB_LOKTX  CHARACTER(3)    NOT NULL
 )
  DATA CAPTURE NONE
  IN USERSPACE2;

ALTER TABLE TH2018.HTX_LEDGER
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

ALTER TABLE TH2018.HTX_LEDGER
  ADD CONSTRAINT SQL141231032120540 PRIMARY KEY
   (NO_REK,
    KD_CAB,
    TGL_TX,
    TIME_STAMP
   );

   --

   CREATE TABLE TH2018.HTX_NOMI
 (NO_REK        VARCHAR(12)     NOT NULL,
  KD_CAB        CHARACTER(3)    NOT NULL,
  TGL_TX        DATE            NOT NULL,
  TIME_STAMP    TIMESTAMP       NOT NULL,
  KD_USER       CHARACTER(5)    NOT NULL,
  KD_TX         CHARACTER(3)    NOT NULL,
  KET_TX        VARCHAR(30)     NOT NULL,
  NO_ARSIP      VARCHAR(10)     NOT NULL,
  SALDO_AKHIR   DECIMAL(15, 2)  NOT NULL,
  DB_KR         CHARACTER(1)    NOT NULL,
  JUMLAH_TX     DECIMAL(15, 2)  NOT NULL,
  KD_SPV        CHARACTER(5)    NOT NULL,
  KD_CAB_LOKTX  CHARACTER(3)    NOT NULL
 )
  DATA CAPTURE NONE
  IN USERSPACE2;

ALTER TABLE TH2018.HTX_NOMI
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

ALTER TABLE TH2018.HTX_NOMI
  ADD CONSTRAINT SQL141231032120540 PRIMARY KEY
   (NO_REK,
    KD_CAB,
    TGL_TX,
    TIME_STAMP
   );
